### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by mueller-ma** [jgraph/plantuml-server#1]
Hey,
when I visit https://exp-plant.draw.io/plantuml4/, the server you mention in https://desk.draw.io/support/solutions/articles/16000061128-how-to-configure-the-draw-io-backend-in-confluence-server, I only see  
```
 Sorry, but things didn't work out as planned.

    Wed May 15 04:59:32 MST 2019
    Request that failed: /plantuml4/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
    Status code: 500
    Exception: org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.index_jsp
```

Same happens if I try to run a self-hosted version.

**Comment by davidjgraph** [comment]
What did you do in draw.io that generated this URL?

**Comment by mueller-ma** [comment]
Nothing :) I just clicked on https://exp-plant.draw.io/plantuml4

**Comment by davidjgraph** [comment]
OK, it's not meant to return anything meaningful. Are you looking for the main PlantUML codebase, maybe?

**Comment by mueller-ma** [comment]
All documentation about how to host your own plantuml server is:

> or host PlantUML server yourself and reference that. Our custom version of PlantUML and server are built at https://github.com/jgraph/plantuml-server/releases. Take the latest release and use a servlet engine, like Tomcat, to host the war.

How do I know if the plantuml server is working if it only returns exceptions?

**Comment by davidjgraph** [comment]
Connect the draw.io instance to it and test a PlantUML diagram.
